name = "Curated"
description = "This is the curated repo for [Gradience](https://github.com/GradienceTeam/Gradience)."
maintainer = "GradienceTeam"
url = "https://usegradience.github.io"
repo = "https://github.com/gradiencepresets/curated"
support = "https://github.com/gradiencepresets/curated/issue" # or matrix ?

base_url = "https://raw.githubusercontent.com/gradiencepresets/{name}/main/{name}.toml"

presets = []

additional = """## New preset process"""

contributing = """Report issues and contribute to the project on [GitHub](https://github.com/GradienceTeam/Gradience)."""
