name: Update repo

on: push

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run generate.py
      run: python generate.py
      shell: sh
